version: "3"
services:
  server_mongo:
    image: mongo:4.4.2
    container_name: server_mongo
    restart: unless-stopped
    ports:
      - 27018:27017
    volumes:
      - mongoData:/data/db
    networks:
      - api-network

  server_redis:
    image: redis:6.0.9
    container_name: server_redis
    restart: unless-stopped
    ports:
      - 6380:6379
    networks:
      - api-network

  server_api:
    build:
      context: .
      dockerfile: Dockerfile
    image: notes-api
    container_name: server_api
    restart: unless-stopped
    env_file: .env
    depends_on:
      - server_mongo
      - server_redis
    links:
      - "server_mongo"
      - "server_redis"
    ports:
      - ${PORT}:${PORT}
    volumes:
      - .:/api
      - /api/node_modules
    networks:
      - api-network
    environment:
      - MONGO_HOST=server_mongo
      - MONGO_PORT=27017
      - MONGO_DB_NAME=notes
      - REDIS_HOST=server_redis
      - REDIS_PORT=6379
      - REDIS_EXPIRATION=60
      - WAIT_HOSTS:server_mongo:27017,server_redis:6379
      - WAIT_HOSTS_TIMEOUT:300
      - WAIT_SLEEP_INTERVAL:30
      - WAIT_HOST_CONNECT_TIMEOUT:30

networks:
  api-network:
    name: api-network
    driver: bridge

volumes:
  mongoData:
